meta:
  environment: ~

update:
  canaries: 1
  max_in_flight: 50
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
  serial: false

jobs:
  - name: carbon_c_relay_leader_z1
    template: carbon-c-relay
    instances: 0
    resource_pool: small_z1
    networks: (( merge ))
    persistent_disk: 0
    properties: {}

networks: (( merge ))

properties:
  carbon-c-relay:
    config: |
     cluster 220net forward 10.9.2.197:2003 proto tcp;
     match ^simon\. send to 220net stop;
